name: Build and Release

permissions:
  contents: write
  packages: write
  issues: write
  deployments: write

on:
  push:
    tags:
      - "v*" # Triggers on tag push (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-pc-windows-gnu
            archive: zip

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Add WebAssembly target
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      # Install wasm-pack
      - name: Install wasm-pack
        run: cargo install wasm-pack

      # Install Terser (for minifying JavaScript)
      - name: Install Terser
        run: npm install -g terser

      # Run tests
      - name: Run tests
        run: cargo test

      # Build WebAssembly
      - name: Build WebAssembly
        run: |
          wasm-pack build --target web --out-dir build/crypto_wasm
          terser build/crypto_wasm/crypto_wasm.js -o build/crypto_wasm/crypto_wasm.lib.min.js --compress --mangle
          terser js/crypto_wasm.js -o build/crypto_wasm/crypto_wasm.min.js --compress --mangle

      # Upload WebAssembly artifacts (v4)
      - name: Upload WebAssembly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-wasm
          path: build/crypto_wasm/

      # Build native binaries using rust-build.action
      - name: Compile CLI for ${{ matrix.target }}
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

      # Upload CLI artifacts (v4)
      - name: Upload CLI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-cli-${{ matrix.target }}
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download WebAssembly artifacts (v4)
      - name: Download WebAssembly artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts-wasm
          path: dist/crypto_wasm/

      # Download CLI artifacts for Linux
      - name: Download Linux CLI artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts-cli-x86_64-unknown-linux-musl
          path: dist/cli/

      # Download CLI artifacts for Windows
      - name: Download Windows CLI artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts-cli-x86_64-pc-windows-gnu
          path: dist/cli/

      # Create a GitHub release
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload WebAssembly assets to the release
      - name: Upload WebAssembly assets (lib.min.js)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/crypto_wasm/crypto_wasm.lib.min.js
          asset_name: crypto_wasm.lib.min.js
          asset_content_type: application/javascript

      - name: Upload WebAssembly assets (min.js)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/crypto_wasm/crypto_wasm.min.js
          asset_name: crypto_wasm.min.js
          asset_content_type: application/javascript

      - name: Upload WebAssembly assets (wasm)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/crypto_wasm/crypto_wasm_bg.wasm
          asset_name: crypto_wasm_bg.wasm
          asset_content_type: application/wasm

      # Upload Linux CLI binary to release
      - name: Upload Linux CLI binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cli/crypto_cli-x86_64-unknown-linux-musl.tar.gz
          asset_name: crypto_cli-linux.tar.gz
          asset_content_type: application/gzip

      # Upload Windows CLI binary to release
      - name: Upload Windows CLI binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cli/crypto_cli-x86_64-pc-windows-gnu.zip
          asset_name: crypto_cli-windows.zip
          asset_content_type: application/zip
